#FROM openjdk:8-jdk-alpine
#EXPOSE 8090
#COPY ./target/Weather-API-0.0.1-SNAPSHOT.jar weather-api-v1.jar
#ADD target/*.jar app.jar
#ENTRYPOINT ["java","-jar", "app.jar"]
#"java","-jar","-Dspring.profiles.active=dev", "productAPI-0.0.1-SNAPSHOT.jar"